spring.application.name=log-analyzer
spring.main.allow-bean-definition-overriding=true
spring.autoconfigure.exclude=\
com.google.cloud.spring.autoconfigure.core.GcpContextAutoConfiguration,\
com.google.cloud.spring.autoconfigure.storage.GcpStorageAutoConfiguration
